name:                boby-alga-toolkit
version:             0.1.0.0
github:              "bobymicroby/boby-alga-toolkit"
license:             BSD3
author:              "Borislav Ivanov"
maintainer:          "boby@boby.dev"
copyright:           "2021 Borislav Ivanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bobymicroby/bobby-alga-toolkit#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - algebraic-graphs
    - uri-encode
    - containers
    - mwc-random
  


executables:
  boby-alga-toolkit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - boby-alga-toolkit
    - transformers
    - haskeline



tests:
  boby-alga-toolkit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bobby-alga-toolkit
